### ISSUE TITLE
Priemtest van Fermat kan niet hoger dan een bepaald getal

### ISSUE THREAD

**Issue by ketelaar** [ketelaar/pws_priemen#2]
Deze error krijg ik als ik het getal 9878974898 invoer

```
Python 3.5.2
Traceback (most recent call last):
  File "python", line 21, in <module>
  File "python", line 8, in fermat
MemoryError
```

**Comment by ketelaar** [comment]
Het is blijkbaar niet een programmeerfout, maar een systeembeperking.

Bij het uitrekenen of het getal 189189891 priem is gebruikte Python bijna 7,5/8 GB van mijn systeemgeheugen. 9878974898 kan Python helemaal niet uitrekenen omdat ik maar 8 GB aan geheugen heb.

![2016-09-14_14-28-09](https://cloud.githubusercontent.com/assets/20154177/18512286/b242d2c0-7a88-11e6-824b-699d89a1e46d.png)
